In [2]:
import pandas as pd
import glob
import os

pasta_dados_brutos = "./dados_brutos/"

padrao_arquivos = os.path.join(pasta_dados_brutos, "*.xlsx")

lista_de_arquivos = glob.glob(padrao_arquivos)


if not lista_de_arquivos:
    print(f"Nenhum arquivo .xlsx foi encontrado no caminho: {pasta_dados_brutos}")
else:
    print(f"Arquivos encontrados: {len(lista_de_arquivos)}")
    print(lista_de_arquivos)

    # Lista vazia para armazenar cada DataFrame lido
    lista_de_dataframes = []

    # Loop para ler cada arquivo e adicioná-lo à lista
    for arquivo in lista_de_arquivos:
        print(f"Lendo o arquivo: {arquivo}")
        df_temp = pd.read_excel(arquivo)
        lista_de_dataframes.append(df_temp)

    # Concatena (junta) todos os DataFrames da lista em um único DataFrame
    # ignore_index=True reinicia o índice do DataFrame final (0, 1, 2, ...)
    df_final = pd.concat(lista_de_dataframes, ignore_index=True)


    # --- 3. VERIFICAÇÃO DO RESULTADO ---
    print("\n--- DataFrame Final ---")
    print("DataFrame combinado com sucesso!")

    # Mostra informações gerais sobre o DataFrame final
    print("\nInformações do DataFrame:")
    df_final.info()

    # Mostra as 5 primeiras linhas do DataFrame final
    print("\nPrimeiras 5 linhas:")
    display(df_final.head())

    # Mostra as 5 últimas linhas do DataFrame final
    print("\nÚltimas 5 linhas:")
    display(df_final.tail())

    # Opcional: Salvar o DataFrame combinado em um novo arquivo Excel
    # df_final.to_excel('relatorio_consolidado.xlsx', index=False)
    # print("\nDataFrame consolidado salvo em 'relatorio_consolidado.xlsx'")

Arquivos encontrados: 27
['./dados_brutos\\Hemoprod_AL.xlsx', './dados_brutos\\Hemoprod_AM.xlsx', './dados_brutos\\Hemoprod_AP.xlsx', './dados_brutos\\Hemoprod_BA.xlsx', './dados_brutos\\Hemoprod_CE.xlsx', './dados_brutos\\Hemoprod_DF.xlsx', './dados_brutos\\Hemoprod_ES.xlsx', './dados_brutos\\Hemoprod_GO.xlsx', './dados_brutos\\Hemoprod_Hemominas.xlsx', './dados_brutos\\Hemoprod_MA.xlsx', './dados_brutos\\Hemoprod_MG.xlsx', './dados_brutos\\Hemoprod_MS.xlsx', './dados_brutos\\Hemoprod_MT.xlsx', './dados_brutos\\Hemoprod_PA.xlsx', './dados_brutos\\Hemoprod_PB.xlsx', './dados_brutos\\Hemoprod_PE.xlsx', './dados_brutos\\Hemoprod_PI.xlsx', './dados_brutos\\Hemoprod_PR.xlsx', './dados_brutos\\Hemoprod_RJ.xlsx', './dados_brutos\\Hemoprod_RN.xlsx', './dados_brutos\\Hemoprod_RO.xlsx', './dados_brutos\\Hemoprod_RR.xlsx', './dados_brutos\\Hemoprod_RS.xlsx', './dados_brutos\\Hemoprod_SC.xlsx', './dados_brutos\\Hemoprod_SE.xlsx', './dados_brutos\\Hemoprod_SP.xlsx', './dados_brutos\\Hemoprod_TO.xlsx']
Lendo o arquivo: ./dados_brutos\Hemoprod_AL.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_AM.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_AP.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_BA.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_CE.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_DF.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_ES.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_GO.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_Hemominas.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_MA.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_MG.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_MS.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_MT.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_PA.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_PB.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_PE.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_PI.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_PR.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_RJ.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_RN.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_RO.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_RR.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_RS.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_SC.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_SE.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_SP.xlsx
Lendo o arquivo: ./dados_brutos\Hemoprod_TO.xlsx

--- DataFrame Final ---
DataFrame combinado com sucesso!

Informações do DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17142 entries, 0 to 17141
Columns: 278 entries, ID da resposta to Município
dtypes: float64(248), object(30)
memory usage: 36.4+ MB

Primeiras 5 linhas:

,ID da resposta,Data de envio,Última página,Idioma inicial,Semente,Código de acesso,Data de início,Data da última ação,Endereço IP,IDENTIFICAÇÃO DO DADO,...,HEMOPROD_3 - Observações,URL de referência,Ano de referência,"Razão Social - Nome Fantasia ATENÇÃO!!! A lista de estabelecimentos abaixo é atualizada frequentemente e deve ser priorizada para preenchimento do nome fantasia. Use a opção ""Outro"" apenas se não for possível identificar o nome do estabelecimento por ela.","Razão Social - Nome Fantasia ATENÇÃO!!! A lista de estabelecimentos abaixo é atualizada frequentemente e deve ser priorizada para preenchimento do nome fantasia. Use a opção ""Outro"" apenas se não for possível identificar o nome do estabelecimento por ela. [Outros]",Período de referência [Outros],Município [Outros],Município ATENÇÃO!!! A lista de municípios abaixo foi atualizada e deve ser priorizada para preenchimento do local.,Município ATENÇÃO!!! A lista de municípios abaixo foi atualizada e deve ser priorizada para preenchimento do local. [Outros],Município
0,21.0,2024-07-03 09:12:00,4.0,pt-BR,NaN,mC2pcyfb6aHYhhG,2024-07-03 09:00:00,2024-07-03 09:12:00,186.249.59.158,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,22.0,2024-07-03 18:36:00,4.0,pt-BR,NaN,FPAwxbAGdnaP0uv,2024-07-03 18:21:00,2024-07-03 18:36:00,186.249.60.28,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,26.0,2024-07-05 18:21:55,4.0,pt-BR,5.371664e+06,VwcXLtA5rfFIUi9,2024-07-05 17:19:26,2024-07-05 18:21:55,206.42.47.96,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,28.0,2024-07-07 18:21:00,4.0,pt-BR,NaN,7qTz7fGLGpNNxUf,2024-07-07 17:40:00,2024-07-07 18:21:00,190.102.52.160,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,29.0,2024-07-07 18:39:39,4.0,pt-BR,1.067738e+09,XpuFs3JEYKeGWPJ,2024-07-07 18:27:15,2024-07-07 18:39:39,190.102.52.160,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Últimas 5 linhas:

,ID da resposta,Data de envio,Última página,Idioma inicial,Semente,Código de acesso,Data de início,Data da última ação,Endereço IP,IDENTIFICAÇÃO DO DADO,...,HEMOPROD_3 - Observações,URL de referência,Ano de referência,"Razão Social - Nome Fantasia ATENÇÃO!!! A lista de estabelecimentos abaixo é atualizada frequentemente e deve ser priorizada para preenchimento do nome fantasia. Use a opção ""Outro"" apenas se não for possível identificar o nome do estabelecimento por ela.","Razão Social - Nome Fantasia ATENÇÃO!!! A lista de estabelecimentos abaixo é atualizada frequentemente e deve ser priorizada para preenchimento do nome fantasia. Use a opção ""Outro"" apenas se não for possível identificar o nome do estabelecimento por ela. [Outros]",Período de referência [Outros],Município [Outros],Município ATENÇÃO!!! A lista de municípios abaixo foi atualizada e deve ser priorizada para preenchimento do local.,Município ATENÇÃO!!! A lista de municípios abaixo foi atualizada e deve ser priorizada para preenchimento do local. [Outros],Município
17137,277.0,2025-09-10 16:37:14,4.0,pt-BR,9.884601e+08,jDwcqGgUtyyIMJb,2025-09-10 16:14:51,2025-09-10 16:37:14,128.201.17.234,NaN,...,NaN,NaN,2025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17138,278.0,2025-09-10 16:52:52,4.0,pt-BR,1.820648e+08,jDwcqGgUtyyIMJb,2025-09-10 16:40:44,2025-09-10 16:52:52,128.201.17.234,NaN,...,NaN,NaN,2025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17139,279.0,2025-09-10 17:15:48,4.0,pt-BR,1.892477e+09,jDwcqGgUtyyIMJb,2025-09-10 16:54:01,2025-09-10 17:15:48,128.201.17.234,NaN,...,NaN,NaN,2025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17140,280.0,2025-09-10 17:24:13,4.0,pt-BR,9.447311e+08,jDwcqGgUtyyIMJb,2025-09-10 17:19:47,2025-09-10 17:24:13,128.201.17.234,NaN,...,NaN,NaN,2025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17141,282.0,2025-09-11 14:56:46,4.0,pt-BR,1.562919e+09,jDwcqGgUtyyIMJb,2025-09-11 14:40:52,2025-09-11 14:56:46,128.201.17.234,NaN,...,NaN,NaN,2025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_final.describe()

,ID da resposta,Última página,Semente,IDENTIFICAÇÃO DO DADO,Ano de referência,2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Espontânea][Aptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Espontânea][Inaptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Reposição][Aptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Reposição][Inaptos],2. Triagem Clínica 2.1 Total de candidatos quanto ao tipo de doação [Autóloga][Aptos],...,7 Reações Transfusionais [Reação Febril não Hemolítica],7 Reações Transfusionais [Reação Hemolítica],7 Reações Transfusionais [Reação Alérgica],7 Reações Transfusionais [Choque Bacteriano],7 Reações Transfusionais [Alterações Metabólicas],7 Reações Transfusionais [Sobrecarga Volêmica],7 Reações Transfusionais [Outras reações ],8. Envio de Plasma para produção de hemoderivados [Plasma Fresco Congelado],8. Envio de Plasma para produção de hemoderivados [Plasma Comum],Ano de referência
count,15988.000000,15988.000000,1.497900e+04,0.0,6223.000000,7090.000000,7090.000000,7077.000000,7077.000000,7073.000000,...,16543.000000,16543.000000,16545.000000,16543.000000,16543.000000,16543.000000,16543.000000,6672.000000,6672.000000,6225.000000
mean,1414.345822,3.999875,1.072138e+09,NaN,2023.889603,989.019323,176.224683,558.237701,103.627808,13.309204,...,0.467569,0.013238,0.387428,0.006105,0.003264,0.053376,0.280844,157.932104,23.720773,2023.978956
std,1524.045538,0.015817,6.201798e+08,NaN,0.901903,9775.679848,1642.803831,4013.008496,600.558016,957.865698,...,4.690959,0.369632,4.475936,0.269829,0.085109,0.766464,9.680531,809.610848,178.448467,0.771463
min,2.000000,2.000000,1.197710e+05,NaN,2022.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2022.000000
25%,327.000000,4.000000,5.299063e+08,NaN,2023.000000,122.000000,16.000000,20.000000,2.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2023.000000
50%,820.000000,4.000000,1.064350e+09,NaN,2024.000000,294.000000,41.000000,144.000000,26.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2024.000000
75%,1909.000000,4.000000,1.616645e+09,NaN,2025.000000,569.750000,96.000000,412.000000,76.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2025.000000
max,5968.000000,4.000000,2.147470e+09,NaN,2025.000000,333820.000000,59966.000000,209116.000000,16460.000000,80431.000000,...,247.000000,37.000000,273.000000,26.000000,6.000000,46.000000,1216.000000,23233.000000,8060.000000,2025.000000